/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 * Run `pnpm generate:types` (with the API running locally) to regenerate.
 */
export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/guest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_guestLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_googleLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all projects in the caller's workspace */
        get: operations["ProjectsController_findAll"];
        put?: never;
        /** Create a project in the caller's workspace */
        post: operations["ProjectsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single project by id */
        get: operations["ProjectsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks in the caller's workspace, paginated */
        get: operations["TasksController_findAll"];
        put?: never;
        /** Create a task in one of the caller's projects */
        post: operations["TasksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single task by id */
        get: operations["TasksController_findOne"];
        put?: never;
        post?: never;
        /** Delete a task */
        delete: operations["TasksController_remove"];
        options?: never;
        head?: never;
        /** Update a task's fields */
        patch: operations["TasksController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PublicUserDto: {
            id: string;
            fullName: string;
            username: string;
            isGuest: boolean;
            avatarUrl: string | null;
        };
        CreateProjectDto: {
            /** @example Website Redesign */
            name: string;
            /**
             * @default NO_PRIORITY
             * @enum {string}
             */
            priority?: "NO_PRIORITY" | "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /**
             * Format: date-time
             * @example 2026-09-01
             */
            dueDate?: string;
        };
        ProjectResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            priority: "NO_PRIORITY" | "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** Format: date-time */
            dueDate: string | null;
            /** Format: uuid */
            workspaceId: string;
            /** Format: uuid */
            leadId: string;
            lead: components["schemas"]["PublicUserDto"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateTaskDto: {
            /** @example Set up CI pipeline */
            title: string;
            /** Format: uuid */
            projectId: string;
            /**
             * @default TODO
             * @enum {string}
             */
            status?: "BACKLOG" | "TODO" | "IN_PROGRESS" | "ON_HOLD" | "DONE";
            /**
             * @default NO_PRIORITY
             * @enum {string}
             */
            priority?: "NO_PRIORITY" | "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /**
             * Format: date-time
             * @example 2026-08-20
             */
            dueDate?: string;
            /** Format: uuid */
            parentTaskId?: string;
        };
        LabelDto: {
            /** Format: uuid */
            id: string;
            name: string;
            color: string;
        };
        TaskResponseDto: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @enum {string} */
            status: "BACKLOG" | "TODO" | "IN_PROGRESS" | "ON_HOLD" | "DONE";
            /** @enum {string} */
            priority: "NO_PRIORITY" | "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** Format: date-time */
            dueDate: string | null;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            parentTaskId: string | null;
            /** Format: uuid */
            reporterId: string;
            reporter: components["schemas"]["PublicUserDto"];
            assignees: components["schemas"]["PublicUserDto"][];
            labels: components["schemas"]["LabelDto"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginationMetaDto: {
            page: number;
            limit: number;
            total: number;
        };
        TaskListResponseDto: {
            data: components["schemas"]["TaskResponseDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        UpdateTaskDto: {
            /** @example Set up CI pipeline */
            title?: string;
            /**
             * @default TODO
             * @enum {string}
             */
            status?: "BACKLOG" | "TODO" | "IN_PROGRESS" | "ON_HOLD" | "DONE";
            /**
             * @default NO_PRIORITY
             * @enum {string}
             */
            priority?: "NO_PRIORITY" | "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /**
             * Format: date-time
             * @example 2026-08-20
             */
            dueDate?: string;
            /** Format: uuid */
            parentTaskId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_guestLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUserDto"];
                };
            };
        };
    };
    AuthController_googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUserDto"];
                };
            };
        };
    };
    ProjectsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponseDto"][];
                };
            };
        };
    };
    ProjectsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectDto"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponseDto"];
                };
            };
        };
    };
    ProjectsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponseDto"];
                };
            };
            /** @description Project not found or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_findAll: {
        parameters: {
            query?: {
                projectId?: string;
                status?: "BACKLOG" | "TODO" | "IN_PROGRESS" | "ON_HOLD" | "DONE";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponseDto"];
                };
            };
        };
    };
    TasksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskDto"];
            };
        };
        responses: {
            /** @description Task created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
            /** @description Project not found or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
            /** @description Task not found or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
            /** @description Task not found or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
