#!/usr/bin/env node
import openapiTS, { astToString } from "openapi-typescript";
import fs from "node:fs";
import path from "node:path";

const envPath = path.resolve(import.meta.dirname, "../.env.local");

if (fs.existsSync(envPath)) {
  process.loadEnvFile(envPath);
  console.log(`Loaded env from ${envPath}`);
} else {
  console.log(`No .env.local found at ${envPath} — falling back to process env / default`);
}

const apiBaseUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3000";
const specUrl = new URL("/api/docs-json", apiBaseUrl);

console.log(`Generating types from ${specUrl}`);

// defaultNonNullable: false — without this, openapi-typescript treats any
// property with an OpenAPI `default` as always-required, since that's
// correct for response types (a defaulted field is always present when you
// read it back) but wrong for request bodies (a default exists precisely
// so the client CAN omit the field). One generated type is shared between
// both directions, so this flag is needed to keep request types honest.
const ast = await openapiTS(specUrl, { defaultNonNullable: false });
const body = astToString(ast);

const header = [
  "/**",
  " * This file was auto-generated by openapi-typescript.",
  " * Do not make direct changes to the file.",
  " * Run `pnpm generate:types` (with the API running locally) to regenerate.",
  " */",
  "",
].join("\n");

const outPath = path.resolve(import.meta.dirname, "../src/lib/api/schema.d.ts");
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, header + body);

console.log(`Written to ${outPath}`);